### ISSUE TITLE
item total in an order is doubled

### ISSUE THREAD

**Issue by Yessi66** [AashikP/item-total-for-wc#3] opened 2022-02-07 12:46 UTC
Hi AashikP, I have never posted anything on github before, so please forgive me if I am not following protocol for posting. I really like using your plugin, but I found an issue, wich is also present when deactivated current theme and plugins. The item total in an order is doubled for an item, wich has the same settings as other variants. Is there anything I can do, to investigate the cause or to fix it?

![order_amount_wrong_total](https://user-images.githubusercontent.com/99182036/152790640-ab359fab-a36a-4c19-9edd-e3114ff3f108.jpg)

**Comment by AashikP** [comment] 2022-02-08 16:01
Hello @Yessi66 👋 

Thank you for reporting this bug. I could replicate this behavior on my own test site where purchasing multiple quantities of different variations of the same variable product  in the same order seems to mess up the item totals:

![https://d.pr/i/7IGM0a+](https://d.pr/i/7IGM0a+)

As of now the extension checks for the product id which I assume to be the root cause of this behavior. Checking for a variation id when a variable product is involved should fix this behavior.

I'm going to investigate further and fix this in the next couple of days.

**Comment by Yessi66** [comment] 2022-02-08 17:48
Hi @AashikP, that's really awesom. If you need anything from me, please let
me know!

Met gezonde groet,




Jessy de Boer
Lisdoddelaan 70
1562 SN Krommenie
06 547 277 40
https://dewpdokter.nl



Op di 8 feb. 2022 om 17:01 schreef AashikP ***@***.***>:

**Comment by AashikP** [comment] 2022-02-14 15:33
Hello @Yessi66 

This issue is now fixed, and a new version is released with a couple more features and tweaks in this PR: https://github.com/AashikP/item-total-for-wc/pull/4

* You can download a copy of the new version here: https://github.com/AashikP/item-total-for-wc/releases/tag/V1.2.0 (`Download Source-code.zip`).
* Please uninstall the previous version before installing this version.

Thank you again for reporting this issue. If you find any other bugs, please feel free to open a new report.

**Closed as completed by AashikP** 2022-02-14 15:33 UTC
Labels: bug

**Comment by Yessi66** [comment] 2022-02-15 18:17
Hi @AashikP , I have installed the new version. Thank you so much!

**Comment by AashikP** [comment] 2022-02-16 01:48
My pleasure 🙇
